export type HomeHeroProject =
  | "ideias"
  | "design"
  | "tech"
  | "people"
  | "brands"
  | "business";

export type HomeHeroShape = "wide" | "tall" | "phone";

export type HomeHeroCard = {
  src: string;
  alt: string;
  project: HomeHeroProject;
  caseId: string;
  width: number;
  height: number;
  shape: HomeHeroShape;
  top: string;
  left: string;
  size: string;
  rotate: number;
  z: number;
  dx: string;
  dy: string;
  delay: string;
  objectPosition?: string;
};

export const homeHeroImages: HomeHeroCard[] = [
  {
    src: "/images/cases/open-startups/cover.webp",
    alt: "Open Startups",
    project: "ideias",
    caseId: "open-startups",
    width: 1600,
    height: 900,
    shape: "wide",
    top: "6%",
    left: "4%",
    size: "46%",
    rotate: -7,
    z: 3,
    dx: "12px",
    dy: "8px",
    delay: "0s, -1.2s",
  },
  {
    src: "/images/cases/open-startups/apps/billboard.webp",
    alt: "Open Startups",
    project: "ideias",
    caseId: "open-startups",
    width: 1600,
    height: 900,
    shape: "wide",
    top: "48%",
    left: "18%",
    size: "40%",
    rotate: 5,
    z: 4,
    dx: "-10px",
    dy: "12px",
    delay: "-2.1s, -4.4s",
  },
  {
    src: "/images/cases/open-startups/archetypes/sage.webp",
    alt: "Open Startups",
    project: "ideias",
    caseId: "open-startups",
    width: 1200,
    height: 1600,
    shape: "tall",
    top: "10%",
    left: "52%",
    size: "24%",
    rotate: 8,
    z: 5,
    dx: "8px",
    dy: "-14px",
    delay: "-3.4s, -6s",
  },
  {
    src: "/images/cases/sestini/showcase/airport.webp",
    alt: "Sestini",
    project: "design",
    caseId: "sestini",
    width: 1920,
    height: 1080,
    shape: "wide",
    top: "38%",
    left: "-4%",
    size: "44%",
    rotate: -4,
    z: 2,
    dx: "14px",
    dy: "-8px",
    delay: "-1.5s, -3s",
  },
  {
    src: "/images/cases/sestini/showcase/suitcase.webp",
    alt: "Sestini",
    project: "design",
    caseId: "sestini",
    width: 1920,
    height: 1080,
    shape: "wide",
    top: "62%",
    left: "42%",
    size: "38%",
    rotate: 6,
    z: 4,
    dx: "-8px",
    dy: "10px",
    delay: "-4.2s, -7.1s",
  },
  {
    src: "/images/cases/sestini/inspire/window-plane.webp",
    alt: "Sestini",
    project: "design",
    caseId: "sestini",
    width: 1210,
    height: 1816,
    shape: "tall",
    top: "-4%",
    left: "28%",
    size: "22%",
    rotate: -9,
    z: 6,
    dx: "6px",
    dy: "12px",
    delay: "-0.8s, -2.6s",
  },
  {
    src: "/images/home/hero/pubg.webp",
    alt: "PUBG",
    project: "tech",
    caseId: "pubg",
    width: 768,
    height: 1024,
    shape: "tall",
    top: "8%",
    left: "8%",
    size: "28%",
    rotate: 4,
    z: 5,
    dx: "8px",
    dy: "-16px",
    delay: "-1.1s, -6.5s",
  },
  {
    src: "/images/home/hero/pubg-mobile.webp",
    alt: "PUBG",
    project: "tech",
    caseId: "pubg",
    width: 375,
    height: 667,
    shape: "phone",
    top: "2%",
    left: "62%",
    size: "18%",
    rotate: -5,
    z: 7,
    dx: "-10px",
    dy: "8px",
    delay: "-3.6s, -2s",
  },
  {
    src: "/images/home/hero/pubg-dashboard.webp",
    alt: "PUBG",
    project: "tech",
    caseId: "pubg",
    width: 885,
    height: 1041,
    shape: "tall",
    top: "44%",
    left: "50%",
    size: "30%",
    rotate: 9,
    z: 4,
    dx: "12px",
    dy: "-8px",
    delay: "-5s, -7.5s",
  },
  {
    src: "/images/cases/meu-playstation/cover.webp",
    alt: "Meu PlayStation",
    project: "people",
    caseId: "meu-playstation",
    width: 683,
    height: 431,
    shape: "wide",
    top: "22%",
    left: "36%",
    size: "34%",
    rotate: -6,
    z: 3,
    dx: "-12px",
    dy: "10px",
    delay: "-2.8s, -5.2s",
  },
  {
    src: "/images/cases/meu-playstation/showcase/desktop-quem-somos.webp",
    alt: "Meu PlayStation",
    project: "people",
    caseId: "meu-playstation",
    width: 1440,
    height: 3829,
    shape: "wide",
    top: "58%",
    left: "6%",
    size: "36%",
    rotate: 3,
    z: 5,
    dx: "10px",
    dy: "-6px",
    delay: "-4.8s, -1.6s",
    objectPosition: "50% 8%",
  },
  {
    src: "/images/cases/meu-playstation/showcase/mobile-quem-somos.webp",
    alt: "Meu PlayStation",
    project: "people",
    caseId: "meu-playstation",
    width: 720,
    height: 5863,
    shape: "phone",
    top: "28%",
    left: "72%",
    size: "16%",
    rotate: 7,
    z: 6,
    dx: "-6px",
    dy: "14px",
    delay: "-6.2s, -3.8s",
    objectPosition: "50% 0%",
  },
  {
    src: "/images/cases/neodent/photos/hero.webp",
    alt: "Neodent",
    project: "brands",
    caseId: "neodent",
    width: 1440,
    height: 1031,
    shape: "wide",
    top: "42%",
    left: "22%",
    size: "48%",
    rotate: 6,
    z: 3,
    dx: "-12px",
    dy: "14px",
    delay: "-2.4s, -4s",
  },
  {
    src: "/images/cases/neodent/photos/about.webp",
    alt: "Neodent",
    project: "brands",
    caseId: "neodent",
    width: 1600,
    height: 1066,
    shape: "wide",
    top: "68%",
    left: "52%",
    size: "36%",
    rotate: -8,
    z: 4,
    dx: "10px",
    dy: "-10px",
    delay: "-5.5s, -8s",
  },
  {
    src: "/images/cases/neodent/screens/mobile-3.webp",
    alt: "Neodent",
    project: "brands",
    caseId: "neodent",
    width: 360,
    height: 899,
    shape: "phone",
    top: "14%",
    left: "78%",
    size: "15%",
    rotate: 4,
    z: 7,
    dx: "-8px",
    dy: "6px",
    delay: "-1.8s, -5.8s",
    objectPosition: "50% 0%",
  },
  {
    src: "/images/cases/charney-companies/photos/dime-skyline.webp",
    alt: "Charney Companies",
    project: "business",
    caseId: "charney-companies",
    width: 2000,
    height: 1334,
    shape: "wide",
    top: "18%",
    left: "-6%",
    size: "42%",
    rotate: 5,
    z: 2,
    dx: "14px",
    dy: "10px",
    delay: "-3.2s, -6.8s",
  },
  {
    src: "/images/cases/charney-companies/photos/greenhouse.webp",
    alt: "Charney Companies",
    project: "business",
    caseId: "charney-companies",
    width: 1400,
    height: 1867,
    shape: "tall",
    top: "50%",
    left: "70%",
    size: "24%",
    rotate: -6,
    z: 5,
    dx: "-10px",
    dy: "8px",
    delay: "-0.6s, -4.9s",
  },
  {
    src: "/images/cases/charney-companies/screens/hero-site.webp",
    alt: "Charney Companies",
    project: "business",
    caseId: "charney-companies",
    width: 1167,
    height: 730,
    shape: "wide",
    top: "72%",
    left: "24%",
    size: "40%",
    rotate: -3,
    z: 6,
    dx: "8px",
    dy: "-12px",
    delay: "-4s, -2.2s",
  },
];
