import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "content/cases");

const caseDirs = {
  syx: "syx",
  "conecte-ai": "conecte-ai",
  cormora: "cormora",
  "charney-companies": "charney-companies",
  pubg: "pubg",
  sestini: "sestini",
  "mon-museu-oscar-niemeyer": "mon-museu",
  "meu-playstation": "meu-playstation",
  neodent: "neodent",
  "harpia-consultoria": "harpia",
};

function gallery(caseId, count, title) {
  const dir = caseDirs[caseId];
  return Array.from({ length: count }, (_, i) => ({
    src: `/images/cases/${dir}/gallery-${i + 1}.webp`,
    alt: `${title} — imagem ${i + 1} — Matilha Estúdio`,
  }));
}

const cases = [
  {
    id: "syx",
    pt: {
      title: "SYX",
      client: "SYX",
      summary: "Marketplace focado na recolocação de máquinas e equipamentos usados",
      challenge: "Traduzir o novo momento da empresa em uma nova marca e reformular a plataforma já existente para uma experiência funcional e agradável para os usuários.",
      solution: "Discovery, rebranding e renaming da antiga Central de Materiais, redesenho e prototipação do marketplace SYX com foco em expansão de mercado.",
      services: ["Design de Serviço", "Branding & Naming", "UI | UX Design"],
      cover: "/images/cases/syx/cover.webp",
      coverAlt: "Case SYX — Matilha Estúdio",
      gallery: gallery("syx", 6, "SYX"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "SYX — Matilha Estúdio", description: "Rebranding e redesign do marketplace SYX para recolocação de máquinas e equipamentos usados." },
    },
    en: {
      title: "SYX",
      client: "SYX",
      summary: "Marketplace focused on relocating used machinery and equipment",
      challenge: "Translate the company's new moment into a new brand and redesign the existing platform for a functional, enjoyable user experience.",
      solution: "Discovery, rebranding and renaming from Central de Materiais, redesign and prototyping of the SYX marketplace focused on market expansion.",
      services: ["Service Design", "Branding & Naming", "UI | UX Design"],
      cover: "/images/cases/syx/cover.webp",
      coverAlt: "SYX case — Matilha Estúdio",
      gallery: gallery("syx", 6, "SYX"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "SYX — Matilha Estúdio", description: "Rebranding and redesign of the SYX marketplace for used machinery and equipment." },
    },
    es: {
      title: "SYX",
      client: "SYX",
      summary: "Marketplace enfocado en la recolocación de máquinas y equipos usados",
      challenge: "Traducir el nuevo momento de la empresa en una nueva marca y reformular la plataforma existente para una experiencia funcional y agradable.",
      solution: "Discovery, rebranding y renaming de Central de Materiais, rediseño y prototipado del marketplace SYX enfocado en la expansión del mercado.",
      services: ["Diseño de Servicio", "Branding & Naming", "UI | UX Design"],
      cover: "/images/cases/syx/cover.webp",
      coverAlt: "Case SYX — Matilha Estúdio",
      gallery: gallery("syx", 6, "SYX"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "SYX — Matilha Estúdio", description: "Rebranding y rediseño del marketplace SYX para máquinas y equipos usados." },
    },
  },
  {
    id: "conecte-ai",
    pt: {
      title: "Conecte.ai",
      client: "Conecte.ai",
      summary: "Empresa especializada em ferramentas digitais para provedores regionais de internet na venda online.",
      challenge: "Possibilitar o desenvolvimento estratégico de soluções a partir do entendimento de demandas e tarefas dos usuários dos serviços.",
      solution: "Pesquisa empática com mapa de modelo mental, thinking styles e jornada do usuário para inovação baseada em tarefas ainda não supridas.",
      services: ["Design de Serviço"],
      cover: "/images/cases/conecte-ai/cover.webp",
      coverAlt: "Case Conecte AI — Matilha Estúdio",
      gallery: gallery("conecte-ai", 4, "Conecte.ai"),
      relatedCases: ["cormora", "meu-playstation"],
      seo: { title: "Conecte.ai — Matilha Estúdio", description: "Design de serviço e pesquisa empática para provedores de internet." },
    },
    en: {
      title: "Conecte.ai",
      client: "Conecte.ai",
      summary: "Company specialized in digital tools for regional internet providers selling online.",
      challenge: "Enable strategic solution development based on understanding user demands and tasks.",
      solution: "Empathic research with mental model map, thinking styles and user journey for innovation based on unmet tasks.",
      services: ["Service Design"],
      cover: "/images/cases/conecte-ai/cover.webp",
      coverAlt: "Conecte AI case — Matilha Estúdio",
      gallery: gallery("conecte-ai", 4, "Conecte.ai"),
      relatedCases: ["cormora", "meu-playstation"],
      seo: { title: "Conecte.ai — Matilha Estúdio", description: "Service design and empathic research for internet providers." },
    },
    es: {
      title: "Conecte.ai",
      client: "Conecte.ai",
      summary: "Empresa especializada en herramientas digitales para proveedores regionales de internet.",
      challenge: "Posibilitar el desarrollo estratégico de soluciones a partir del entendimiento de las demandas y tareas de los usuarios.",
      solution: "Investigación empática con mapa de modelo mental, thinking styles y journey del usuario para innovación basada en tareas no cubiertas.",
      services: ["Diseño de Servicio"],
      cover: "/images/cases/conecte-ai/cover.webp",
      coverAlt: "Case Conecte AI — Matilha Estúdio",
      gallery: gallery("conecte-ai", 4, "Conecte.ai"),
      relatedCases: ["cormora", "meu-playstation"],
      seo: { title: "Conecte.ai — Matilha Estúdio", description: "Diseño de servicio e investigación empática para proveedores de internet." },
    },
  },
  {
    id: "cormora",
    pt: {
      title: "Cormora",
      client: "Cormora",
      summary: "Plataforma de gerenciamento de viagens de turismo para consultores centralizarem seus negócios.",
      challenge: "Criar um produto White Label modular, intuitivo e simples para agentes de turismo gerenciarem seus negócios de viagem.",
      solution: "Discovery, roadmap de inovação, branding e naming, UI/UX e desenvolvimento da plataforma white label Cormora.",
      services: ["Branding & Naming", "Design de Serviço", "UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/cormora/cover.webp",
      coverAlt: "Case Cormora — Matilha Estúdio",
      gallery: gallery("cormora", 6, "Cormora"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "Cormora — Matilha Estúdio", description: "Plataforma white label de turismo — branding, UX e desenvolvimento." },
    },
    en: {
      title: "Cormora",
      client: "Cormora",
      summary: "Travel management platform for consultants to centralize their business.",
      challenge: "Create a modular, intuitive white-label product for travel agents to manage their travel business.",
      solution: "Discovery, innovation roadmap, branding and naming, UI/UX and development of the Cormora white-label platform.",
      services: ["Branding & Naming", "Service Design", "UI | UX Design", "Development & Tech"],
      cover: "/images/cases/cormora/cover.webp",
      coverAlt: "Cormora case — Matilha Estúdio",
      gallery: gallery("cormora", 6, "Cormora"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "Cormora — Matilha Estúdio", description: "White-label travel platform — branding, UX and development." },
    },
    es: {
      title: "Cormora",
      client: "Cormora",
      summary: "Plataforma de gestión de viajes para que consultores centralicen sus negocios.",
      challenge: "Crear un producto white label modular e intuitivo para agentes de turismo.",
      solution: "Discovery, roadmap de innovación, branding y naming, UI/UX y desarrollo de la plataforma Cormora.",
      services: ["Branding & Naming", "Diseño de Servicio", "UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/cormora/cover.webp",
      coverAlt: "Case Cormora — Matilha Estúdio",
      gallery: gallery("cormora", 6, "Cormora"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "Cormora — Matilha Estúdio", description: "Plataforma white label de turismo — branding, UX y desarrollo." },
    },
  },
  {
    id: "charney-companies",
    pt: {
      title: "Charney Companies",
      client: "Charney Companies",
      summary: "Organização imobiliária verticalmente integrada: incorporação, corretagem e gestão de propriedades.",
      challenge: "Projetar e desenvolver o novo site da Charney alinhado com a nova marca da empresa.",
      solution: "Redesign do website com base no novo manual de marca e nos problemas identificados no site anterior.",
      services: ["UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/charney-companies/cover.webp",
      coverAlt: "Case Charney Companies — Matilha Estúdio",
      gallery: gallery("charney-companies", 6, "Charney Companies"),
      relatedCases: ["cormora", "sestini"],
      seo: { title: "Charney Companies — Matilha Estúdio", description: "Redesign do website imobiliário Charney Companies." },
    },
    en: {
      title: "Charney Companies",
      client: "Charney Companies",
      summary: "Vertically integrated real estate organization: development, brokerage and property management.",
      challenge: "Design and develop Charney's new website aligned with the company's new brand.",
      solution: "Website redesign based on the new brand guidelines and issues identified on the previous site.",
      services: ["UI | UX Design", "Development & Tech"],
      cover: "/images/cases/charney-companies/cover.webp",
      coverAlt: "Charney Companies case — Matilha Estúdio",
      gallery: gallery("charney-companies", 6, "Charney Companies"),
      relatedCases: ["cormora", "sestini"],
      seo: { title: "Charney Companies — Matilha Estúdio", description: "Charney Companies real estate website redesign." },
    },
    es: {
      title: "Charney Companies",
      client: "Charney Companies",
      summary: "Organización inmobiliaria verticalmente integrada: incorporación, corretaje y gestión de propiedades.",
      challenge: "Proyectar y desarrollar el nuevo sitio de Charney alineado con la nueva marca.",
      solution: "Rediseño del website basado en el nuevo manual de marca y problemas del sitio anterior.",
      services: ["UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/charney-companies/cover.webp",
      coverAlt: "Case Charney Companies — Matilha Estúdio",
      gallery: gallery("charney-companies", 6, "Charney Companies"),
      relatedCases: ["cormora", "sestini"],
      seo: { title: "Charney Companies — Matilha Estúdio", description: "Rediseño del sitio inmobiliario Charney Companies." },
    },
  },
  {
    id: "pubg",
    pt: {
      title: "PUBG",
      client: "PUBG",
      summary: "O Battle Royale mais jogado do mundo.",
      challenge: "Melhorar e unificar a experiência do usuário final dentro do site mundial e regional da marca PUBG.",
      solution: "Discovery com jogadores ao redor do mundo, redesign das plataformas e desenvolvimento front e back-end.",
      services: ["Design de Serviço", "UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/pubg/cover.webp",
      coverAlt: "Case PUBG — Matilha Estúdio",
      gallery: gallery("pubg", 6, "PUBG"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "PUBG — Matilha Estúdio", description: "Redesign e unificação da experiência do site PUBG." },
    },
    en: {
      title: "PUBG",
      client: "PUBG",
      summary: "The world's most played Battle Royale.",
      challenge: "Improve and unify the end-user experience across PUBG's global and regional websites.",
      solution: "Discovery with players worldwide, platform redesign and front and back-end development.",
      services: ["Service Design", "UI | UX Design", "Development & Tech"],
      cover: "/images/cases/pubg/cover.webp",
      coverAlt: "PUBG case — Matilha Estúdio",
      gallery: gallery("pubg", 6, "PUBG"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "PUBG — Matilha Estúdio", description: "PUBG website experience redesign and unification." },
    },
    es: {
      title: "PUBG",
      client: "PUBG",
      summary: "El Battle Royale más jugado del mundo.",
      challenge: "Mejorar y unificar la experiencia del usuario en los sitios global y regional de PUBG.",
      solution: "Discovery con jugadores de todo el mundo, rediseño de plataformas y desarrollo front y back-end.",
      services: ["Diseño de Servicio", "UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/pubg/cover.webp",
      coverAlt: "Case PUBG — Matilha Estúdio",
      gallery: gallery("pubg", 6, "PUBG"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "PUBG — Matilha Estúdio", description: "Rediseño y unificación de la experiencia del sitio PUBG." },
    },
  },
  {
    id: "sestini",
    pt: {
      title: "Brandbook Sestini",
      client: "Sestini",
      summary: "Empresa referência nacional em malas de viagem, mochilas, bolsas e acessórios.",
      challenge: "Baseando-se no novo logo da Sestini, criar o Manual de Marca para padronizar a comunicação institucional.",
      solution: "Brandbook com regras de identidade visual, aplicações, dimensões mínimas e paleta institucional de cores.",
      services: ["Branding"],
      cover: "/images/cases/sestini/cover.webp",
      coverAlt: "Case Sestini — Matilha Estúdio",
      gallery: gallery("sestini", 6, "Sestini"),
      relatedCases: ["charney-companies", "neodent"],
      seo: { title: "Sestini — Matilha Estúdio", description: "Brandbook e manual de marca para a Sestini." },
    },
    en: {
      title: "Sestini Brandbook",
      client: "Sestini",
      summary: "National reference company in travel bags, backpacks, purses and accessories.",
      challenge: "Based on Sestini's new logo, create the Brand Manual to standardize institutional communication.",
      solution: "Brandbook with visual identity rules, applications, minimum dimensions and institutional color palette.",
      services: ["Branding"],
      cover: "/images/cases/sestini/cover.webp",
      coverAlt: "Sestini case — Matilha Estúdio",
      gallery: gallery("sestini", 6, "Sestini"),
      relatedCases: ["charney-companies", "neodent"],
      seo: { title: "Sestini — Matilha Estúdio", description: "Brandbook and brand manual for Sestini." },
    },
    es: {
      title: "Brandbook Sestini",
      client: "Sestini",
      summary: "Empresa referencia nacional en maletas, mochilas, bolsos y accesorios.",
      challenge: "Basándose en el nuevo logo de Sestini, crear el Manual de Marca para estandarizar la comunicación institucional.",
      solution: "Brandbook con reglas de identidad visual, aplicaciones, dimensiones mínimas y paleta institucional.",
      services: ["Branding"],
      cover: "/images/cases/sestini/cover.webp",
      coverAlt: "Case Sestini — Matilha Estúdio",
      gallery: gallery("sestini", 6, "Sestini"),
      relatedCases: ["charney-companies", "neodent"],
      seo: { title: "Sestini — Matilha Estúdio", description: "Brandbook y manual de marca para Sestini." },
    },
  },
  {
    id: "mon-museu-oscar-niemeyer",
    pt: {
      title: "Museu Oscar Niemeyer",
      client: "MON",
      summary: "O maior museu de arte da América Latina.",
      challenge: "Tornar a experiência do site agradável e útil, unificando informações dos diferentes setores do museu.",
      solution: "Pesquisa de serviço, redesign com identidade visual existente e desenvolvimento incluindo loja virtual e migração de conteúdo.",
      services: ["Design de Serviço", "UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/mon-museu/cover.webp",
      coverAlt: "Case MON — Matilha Estúdio",
      gallery: gallery("mon-museu-oscar-niemeyer", 6, "MON"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "MON — Matilha Estúdio", description: "Redesign e desenvolvimento do site do Museu Oscar Niemeyer." },
    },
    en: {
      title: "Oscar Niemeyer Museum",
      client: "MON",
      summary: "The largest art museum in Latin America.",
      challenge: "Make the website experience pleasant and useful, unifying information from different museum departments.",
      solution: "Service research, redesign with existing visual identity and development including online store and content migration.",
      services: ["Service Design", "UI | UX Design", "Development & Tech"],
      cover: "/images/cases/mon-museu/cover.webp",
      coverAlt: "MON case — Matilha Estúdio",
      gallery: gallery("mon-museu-oscar-niemeyer", 6, "MON"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "MON — Matilha Estúdio", description: "Oscar Niemeyer Museum website redesign and development." },
    },
    es: {
      title: "Museo Oscar Niemeyer",
      client: "MON",
      summary: "El museo de arte más grande de América Latina.",
      challenge: "Hacer la experiencia del sitio agradable y útil, unificando información de los diferentes sectores del museo.",
      solution: "Investigación de servicio, rediseño con identidad visual existente y desarrollo incluyendo tienda virtual y migración de contenido.",
      services: ["Diseño de Servicio", "UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/mon-museu/cover.webp",
      coverAlt: "Case MON — Matilha Estúdio",
      gallery: gallery("mon-museu-oscar-niemeyer", 6, "MON"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "MON — Matilha Estúdio", description: "Rediseño y desarrollo del sitio del Museo Oscar Niemeyer." },
    },
  },
  {
    id: "meu-playstation",
    pt: {
      title: "Meu PlayStation",
      client: "Meu PlayStation",
      summary: "O maior canal de notícias sobre PlayStation das Américas.",
      challenge: "Redesenhar o site de notícias do MeuPS para melhorar a experiência e interação do usuário final.",
      solution: "Discovery, roadmap de inovação e UI design com imersão no universo gamer e contato com usuários da plataforma.",
      services: ["Design de Serviço", "UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/meu-playstation/cover.webp",
      coverAlt: "Case Meu PlayStation — Matilha Estúdio",
      gallery: gallery("meu-playstation", 6, "Meu PlayStation"),
      relatedCases: ["conecte-ai", "mon-museu-oscar-niemeyer"],
      seo: { title: "Meu PlayStation — Matilha Estúdio", description: "Redesign do site de notícias Meu PlayStation." },
    },
    en: {
      title: "My PlayStation",
      client: "My PlayStation",
      summary: "The largest PlayStation news channel in the Americas.",
      challenge: "Redesign the MeuPS news site to improve end-user experience and interaction.",
      solution: "Discovery, innovation roadmap and UI design with deep immersion in the gaming universe and platform users.",
      services: ["Service Design", "UI | UX Design", "Development & Tech"],
      cover: "/images/cases/meu-playstation/cover.webp",
      coverAlt: "My PlayStation case — Matilha Estúdio",
      gallery: gallery("meu-playstation", 6, "My PlayStation"),
      relatedCases: ["conecte-ai", "mon-museu-oscar-niemeyer"],
      seo: { title: "My PlayStation — Matilha Estúdio", description: "My PlayStation news site redesign." },
    },
    es: {
      title: "Mi PlayStation",
      client: "Mi PlayStation",
      summary: "El mayor canal de noticias sobre PlayStation de las Américas.",
      challenge: "Rediseñar el sitio de noticias MeuPS para mejorar la experiencia e interacción del usuario.",
      solution: "Discovery, roadmap de innovación y UI design con inmersión en el universo gamer y usuarios de la plataforma.",
      services: ["Diseño de Servicio", "UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/meu-playstation/cover.webp",
      coverAlt: "Case Mi PlayStation — Matilha Estúdio",
      gallery: gallery("meu-playstation", 6, "Mi PlayStation"),
      relatedCases: ["conecte-ai", "mon-museu-oscar-niemeyer"],
      seo: { title: "Mi PlayStation — Matilha Estúdio", description: "Rediseño del sitio de noticias Mi PlayStation." },
    },
  },
  {
    id: "neodent",
    pt: {
      title: "Neodent",
      client: "Neodent",
      summary: "Landing page para ortodontistas, simplificando o portfólio de produtos com experiência imersiva.",
      challenge: "Criar uma landing que simplifique o portfólio de produtos da Neodent, variando idioma e produtos por localidade.",
      solution: "Landing page com produtos destacados por país — 14 países e 7 idiomas com configuração diferente para cada um.",
      services: ["UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/neodent/cover.webp",
      coverAlt: "Case Neodent — Matilha Estúdio",
      gallery: gallery("neodent", 4, "Neodent"),
      relatedCases: ["sestini", "charney-companies"],
      seo: { title: "Neodent — Matilha Estúdio", description: "Landing page multilíngue para portfólio Neodent." },
    },
    en: {
      title: "Neodent",
      client: "Neodent",
      summary: "Landing page for orthodontists, simplifying the product portfolio with an immersive experience.",
      challenge: "Create a landing page that simplifies Neodent's product portfolio, varying language and products by location.",
      solution: "Landing page highlighting products by country — 14 countries and 7 languages with different configuration for each.",
      services: ["UI | UX Design", "Development & Tech"],
      cover: "/images/cases/neodent/cover.webp",
      coverAlt: "Neodent case — Matilha Estúdio",
      gallery: gallery("neodent", 4, "Neodent"),
      relatedCases: ["sestini", "charney-companies"],
      seo: { title: "Neodent — Matilha Estúdio", description: "Multilingual landing page for Neodent portfolio." },
    },
    es: {
      title: "Neodent",
      client: "Neodent",
      summary: "Landing page para ortodoncistas, simplificando el portafolio de productos con experiencia inmersiva.",
      challenge: "Crear una landing que simplifique el portafolio de Neodent, variando idioma y productos según la localidad.",
      solution: "Landing page con productos destacados por país — 14 países y 7 idiomas con configuración diferente para cada uno.",
      services: ["UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/neodent/cover.webp",
      coverAlt: "Case Neodent — Matilha Estúdio",
      gallery: gallery("neodent", 4, "Neodent"),
      relatedCases: ["sestini", "charney-companies"],
      seo: { title: "Neodent — Matilha Estúdio", description: "Landing page multilingüe para portafolio Neodent." },
    },
  },
  {
    id: "harpia-consultoria",
    pt: {
      title: "Harpia Consultoria",
      client: "Harpia Consultoria",
      summary: "Consultoria de processos, solução web, aplicativos mobile e sistema ERP.",
      challenge: "Criar uma nova interface para o website da Harpia, explorando o impacto e força que a marca representa.",
      solution: "Redesign do website com mapas topográficos como textura, integração API WhatsApp e gerenciamento de newsletter.",
      services: ["UI | UX Design", "Desenvolvimento e Tech"],
      cover: "/images/cases/harpia/cover.webp",
      coverAlt: "Case Harpia Consultoria — Matilha Estúdio",
      gallery: gallery("harpia-consultoria", 6, "Harpia Consultoria"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "Harpia Consultoria — Matilha Estúdio", description: "Redesign do website Harpia Consultoria." },
    },
    en: {
      title: "Harpia Consultoria",
      client: "Harpia Consultoria",
      summary: "Process consulting, web solutions, mobile apps and ERP system.",
      challenge: "Create a new interface for Harpia's website, exploring the impact and strength the brand represents.",
      solution: "Website redesign with topographic maps as texture, WhatsApp API integration and newsletter management.",
      services: ["UI | UX Design", "Development & Tech"],
      cover: "/images/cases/harpia/cover.webp",
      coverAlt: "Harpia Consultoria case — Matilha Estúdio",
      gallery: gallery("harpia-consultoria", 6, "Harpia Consultoria"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "Harpia Consultoria — Matilha Estúdio", description: "Harpia Consultoria website redesign." },
    },
    es: {
      title: "Harpia Consultoria",
      client: "Harpia Consultoria",
      summary: "Consultoría de procesos, solución web, apps móviles y sistema ERP.",
      challenge: "Crear una nueva interfaz para el sitio de Harpia, explorando el impacto y fuerza de la marca.",
      solution: "Rediseño del sitio con mapas topográficos como textura, integración API WhatsApp y gestión de newsletter.",
      services: ["UI | UX Design", "Desarrollo y Tech"],
      cover: "/images/cases/harpia/cover.webp",
      coverAlt: "Case Harpia Consultoria — Matilha Estúdio",
      gallery: gallery("harpia-consultoria", 6, "Harpia Consultoria"),
      relatedCases: ["charney-companies", "sestini"],
      seo: { title: "Harpia Consultoria — Matilha Estúdio", description: "Rediseño del sitio Harpia Consultoria." },
    },
  },
];

const slugs = {
  syx: { pt: "syx", en: "syx", es: "syx" },
  "conecte-ai": { pt: "conecte-ai", en: "conecte-ai", es: "conecte-ai" },
  cormora: { pt: "cormora", en: "cormora", es: "cormora" },
  "charney-companies": { pt: "charney-companies", en: "charney-companies", es: "charney-companies" },
  pubg: { pt: "pubg", en: "pubg", es: "pubg" },
  sestini: { pt: "sestini", en: "sestini", es: "sestini" },
  "mon-museu-oscar-niemeyer": { pt: "mon-museu-oscar-niemeyer", en: "mon-oscar-niemeyer-museum", es: "museo-oscar-niemeyer" },
  "meu-playstation": { pt: "meu-playstation", en: "my-playstation", es: "mi-playstation" },
  neodent: { pt: "neodent", en: "neodent", es: "neodent" },
  "harpia-consultoria": { pt: "harpia-consultoria", en: "harpia-consultoria", es: "harpia-consultoria" },
};

fs.mkdirSync(OUT, { recursive: true });

for (const c of cases) {
  for (const locale of ["pt-br", "pt-pt", "en", "es"]) {
    const data = {
      id: c.id,
      slug: slugs[c.id][locale],
      ...c[locale],
    };
    fs.writeFileSync(
      path.join(OUT, `${c.id}.${locale}.json`),
      JSON.stringify(data, null, 2) + "\n",
    );
  }
}

console.log(`Generated ${cases.length * 3} case JSON files`);
